#!/bin/bash
#
#skript mis väljastab sisestatud numbrite summa
echo -n "Sisesta arv: "
read arv
summa=0
while [ $arv -ne 0 ]
do
jaak=$(($arv % 10))
summa=$(($summa + $jaak))
arv=$(($arv / 10))
done
echo "Sisestatud numbrite summa on $summa"
#
#skripti lõpp
